name: Pre-Commit

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

on:
  push:
    branches:
      - main
    tags: ["*"]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
      - uses: julia-actions/cache@v2
      - run: julia -e 'using Pkg; Pkg.add("JuliaFormatter")'
      - uses: astral-sh/setup-uv@v6
      - run: uv tool install pre-commit
      - run: pre-commit run --all-files --show-diff-on-failure --color always